In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
show = pd.DataFrame

In [40]:
N = 5
Δ = 3

In [17]:
s0 = np.eye(2,2)
sx = np.array([[0,1],[1,0]])
sy = np.array([[0,-1j],[1j,0]])
sz = np.array([[1,0],[0,-1]])

basis0 = np.array([[1],[0]])
basis1 = np.array([[0],[1]])

In [36]:
show(s0)

0    1
0  1.0  0.0
1  0.0  1.0

In [37]:
show(sx)

0  1
0  0  1
1  1  0

In [38]:
show(sy)

0         1
0  0.0+0.0j -0.0-1.0j
1  0.0+1.0j  0.0+0.0j

In [39]:
show(sz)

0  1
0  1  0
1  0 -1

In [19]:
basis0, basis1

(array([[1],
        [0]]),
 array([[0],
        [1]]))

In [45]:
def spin_operator(spin_matrix, position):
    s = [s0, sx, sy, sz]
    S_i = s[spin_matrix] if position==0 else s0
    for i in range(1,N):
        S_i = np.kron(S_i, s0 if i != position else s[spin_matrix])
    return S_i

### Open Boundary

In [46]:
H = spin_operator(1,0)@spin_operator(1,1) + spin_operator(2,0)@spin_operator(2,1) + Δ*spin_operator(3,0)@spin_operator(3,1)

for i in range(1,N):
    H += spin_operator(1,i)@spin_operator(1,i+1) + spin_operator(2,i)@spin_operator(2,i+1) + Δ*spin_operator(3,i)@spin_operator(3,i+1)

In [48]:
np.linalg.eigvalsh(H)

array([-16.7615807 , -13.03014287, -11.28192377,  -9.53172632,
        -7.82937351,  -7.13195475,  -7.12272586,  -5.58752463,
        -4.8482691 ,  -4.2701781 ,  -3.23356191,  -2.68623384,
        -2.2518989 ,  -1.23557292,  -0.36956382,   0.24864358,
         0.54946768,   1.4203986 ,   2.05706241,   2.42344571,
         3.1746348 ,   4.03927537,   4.14001451,   4.99831886,
         5.26717379,   6.48055299,   7.74699636,   9.47165694,
         9.55278351,   9.83651962,  10.59616689,  15.16911939])